import { NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { createClient } from '@supabase/supabase-js';
import {
  createKieTask,
  getKieTaskResult,
  getKieModelConfig,
  analyzeWithFallback,
  imageUrlToBase64,
  downloadImage,
  GeminiMessage,
  NanoBananaInput,
} from '@/lib/kie-client';
import { getPromptWithVariables } from '@/lib/get-ai-prompt';
import { rateLimit, RATE_LIMITS } from '@/lib/security';

export const runtime = 'nodejs';
export const maxDuration = 120;
export const dynamic = 'force-dynamic';

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

/**
 * Edit a generated static ad with AI
 * 
 * POST /api/static-ads/edit
 * Body: {
 *   generationId: string,
 *   editInstructions: string (in Spanish)
 * }
 */
export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) return new NextResponse('Unauthorized', { status: 401 });

    const rl = await rateLimit(`static-ads-edit:${userId}`, RATE_LIMITS.generation.limit, RATE_LIMITS.generation.windowMs);
    if (!rl.success) {
      return NextResponse.json({ error: 'Demasiadas solicitudes. Intenta en un momento.' }, { status: 429 });
    }

    const body = await req.json();
    const { generationId, editInstructions } = body;

    if (!generationId) {
      return NextResponse.json({ error: 'Missing generationId' }, { status: 400 });
    }
    if (!editInstructions?.trim()) {
      return NextResponse.json({ error: 'Missing editInstructions' }, { status: 400 });
    }

    console.log(`[EDIT] Starting edit for ${generationId}`);

    // Fetch the original generation
    const { data: generation, error: fetchError } = await supabaseAdmin
      .from('generations')
      .select('*')
      .eq('id', generationId)
      .eq('clerk_user_id', userId)
      .single();

    if (fetchError || !generation) {
      return NextResponse.json({ error: 'Generation not found' }, { status: 404 });
    }

    if (generation.status !== 'completed' || !generation.result_url) {
      return NextResponse.json({ error: 'Can only edit completed generations' }, { status: 400 });
    }

    const { input_data, result_url, project_id } = generation;
    const { productName, generatedPrompt, productImages, productImage } = input_data || {};

    // Check credits
    const { data: userCredits } = await supabaseAdmin
      .from('user_credits')
      .select('credits')
      .eq('clerk_user_id', userId)
      .single();

    const editCost = 14; // Same cost as a new generation
    if (!userCredits || userCredits.credits < editCost) {
      return NextResponse.json({ error: 'Insufficient credits' }, { status: 402 });
    }

    // Deduct credits
    await supabaseAdmin
      .from('user_credits')
      .update({ credits: userCredits.credits - editCost })
      .eq('clerk_user_id', userId);

    console.log(`[EDIT] Generating new prompt with edit instructions...`);

    // Get edit prompt template
    const editPromptTemplate = await getPromptWithVariables('static_ads_edit_instructions', {
      ORIGINAL_PROMPT: generatedPrompt || 'Professional product photography',
      USER_EDIT_INSTRUCTIONS: editInstructions,
      PRODUCT_NAME: productName || 'Product'
    });

    // Convert current image to base64 for reference
    let currentImageBase64 = '';
    try {
      currentImageBase64 = await imageUrlToBase64(result_url);
    } catch (e) {
      console.log(`[EDIT] Could not convert current image: ${e}`);
    }

    // Build messages for Gemini
    const imageContent: Array<{ type: 'text'; text: string } | { type: 'image_url'; image_url: { url: string } }> = [
      { type: 'text', text: 'Generate the edited prompt based on the user instructions.' }
    ];

    if (currentImageBase64) {
      imageContent.push({ type: 'image_url', image_url: { url: currentImageBase64 } });
    }

    const messages: GeminiMessage[] = [
      { role: 'developer', content: editPromptTemplate },
      { role: 'user', content: imageContent }
    ];

    // Generate new prompt using whatever analysis model the admin has configured.
    // Default is Gemini 3 Pro; falls back to Gemini Flash 2.0 on transient errors.
    const { analysisModel } = await getKieModelConfig();
    const { text: newPrompt, modelUsed } = await analyzeWithFallback(analysisModel, messages, {
      temperature: 0.5,
      maxTokens: 2000,
    });

    console.log(`[EDIT] New prompt generated by ${modelUsed}: ${newPrompt.substring(0, 80)}...`);

    // Prepare product images (max 8)
    const allImages: string[] = productImages || (productImage ? [productImage] : []);
    const imageInputs = allImages.slice(0, 7).filter(url => url?.startsWith('http'));
    
    // Add the current generated image as reference (if we have space)
    if (imageInputs.length < 8 && result_url?.startsWith('http')) {
      imageInputs.push(result_url);
    }

    console.log(`[EDIT] Creating Nano Banana task with ${imageInputs.length} images...`);

    const { generationModel } = await getKieModelConfig();

    // Preserve the template's aspect ratio across edits — each row from the
    // pipeline carries the detected ratio under input_data.templateAspectRatio.
    // Falls back to '1:1' for legacy rows that pre-date aspect detection.
    const editAspect = (input_data?.templateAspectRatio || '1:1') as NanoBananaInput['aspect_ratio'];

    // Create new generation task
    const nanoBananaInput: NanoBananaInput = {
      prompt: newPrompt,
      image_input: imageInputs,
      aspect_ratio: editAspect,
      resolution: '2K',
      output_format: 'png'
    };

    const taskId = await createKieTask(generationModel, nanoBananaInput);
    console.log(`[EDIT] Task created: ${taskId}`);

    // Determine next version number
    const currentVersion = generation.version || 1;
    const nextVersion = currentVersion + 1;

    // Create a new generation record for the edit
    const { data: newGeneration, error: insertError } = await supabaseAdmin
      .from('generations')
      .insert({
        clerk_user_id: userId,
        type: 'static_ad_generation',
        status: 'generating',
        project_id: project_id,
        cost: editCost,
        version: nextVersion,
        parent_id: generationId,
        input_data: {
          ...input_data,
          generatedPrompt: newPrompt,
          generationTaskId: taskId,
          editedFrom: generationId,
          editInstructions: editInstructions
        }
      })
      .select()
      .single();

    if (insertError) {
      console.error('[EDIT] Failed to create generation record:', insertError);
      // Refund credits
      await supabaseAdmin
        .from('user_credits')
        .update({ credits: userCredits.credits })
        .eq('clerk_user_id', userId);
      return NextResponse.json({ error: 'Failed to create edit record' }, { status: 500 });
    }

    // Poll for result (with timeout)
    console.log(`[EDIT] Polling for result...`);
    const maxAttempts = 60;
    const pollInterval = 3000;

    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      await new Promise(resolve => setTimeout(resolve, pollInterval));

      try {
        const result = await getKieTaskResult(taskId);

        if (result.status === 'SUCCESS') {
          let resultUrl = '';
          if (typeof result.result === 'string') {
            resultUrl = result.result;
          } else if (Array.isArray(result.result)) {
            resultUrl = result.result[0];
          } else if (result.result?.url) {
            resultUrl = result.result.url;
          } else if (result.result?.output) {
            resultUrl = Array.isArray(result.result.output) 
              ? result.result.output[0] 
              : result.result.output;
          }

          if (resultUrl) {
            // Download and upload to storage
            try {
              const imageBuffer = await downloadImage(resultUrl);
              const fileName = `${project_id}/${newGeneration.id}_${Date.now()}.png`;
              
              await supabaseAdmin.storage
                .from('generations')
                .upload(fileName, imageBuffer, { contentType: 'image/png', upsert: true });

              const { data: urlData } = supabaseAdmin.storage
                .from('generations')
                .getPublicUrl(fileName);

              resultUrl = urlData.publicUrl;
            } catch (e) {
              console.log(`[EDIT] Storage upload failed, using kie.ai URL: ${e}`);
            }

            // Update generation with result
            await supabaseAdmin.from('generations').update({
              status: 'completed',
              result_url: resultUrl,
              updated_at: new Date().toISOString()
            }).eq('id', newGeneration.id);

            console.log(`[EDIT] SUCCESS! Result: ${resultUrl}`);
            return NextResponse.json({
              success: true,
              newGenerationId: newGeneration.id,
              resultUrl,
              version: nextVersion,
              prompt: newPrompt
            });
          }
        } else if (result.status === 'FAILED') {
          await supabaseAdmin.from('generations').update({
            status: 'failed',
            error_message: result.error || 'Generation failed',
            updated_at: new Date().toISOString()
          }).eq('id', newGeneration.id);

          // Refund credits on failure
          await supabaseAdmin
            .from('user_credits')
            .update({ credits: userCredits.credits })
            .eq('clerk_user_id', userId);

          return NextResponse.json({ 
            error: result.error || 'Generation failed' 
          }, { status: 500 });
        }
        // PENDING/PROCESSING - continue polling
      } catch (pollError: any) {
        console.error(`[EDIT] Poll error:`, pollError.message);
      }
    }

    // Timeout - mark as failed
    await supabaseAdmin.from('generations').update({
      status: 'failed',
      error_message: 'Generation timed out',
      updated_at: new Date().toISOString()
    }).eq('id', newGeneration.id);

    return NextResponse.json({ error: 'Generation timed out' }, { status: 504 });

  } catch (error: any) {
    console.error('[EDIT] Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
